### ISSUE TITLE
add codecov to README

### ISSUE THREAD

**Issue by GitMensch** [danielealbano/lcov-action#7]
The suggestion about adding codecov to the documentation is great, will update the readme, thanks!

_Originally posted by @danielealbano in https://github.com/danielealbano/lcov-action/issues/6#issuecomment-1167478476_

**Comment by LecrisUT** [comment]
Is it simply running the codecov action after this one without gcov?

**Comment by GitMensch** [comment]
Yes, that was the point to add in the readme (codecov needs the lcov data, which may be produced by this action).

**Comment by danielealbano** [comment]
This is how I use the action to generate the code coverage for codecov and then how I use the codecov action to upload it

https://github.com/danielealbano/cachegrand/blob/main/.github/workflows/build_and_test.yml#L76
https://github.com/danielealbano/cachegrand/blob/main/.github/workflows/build_and_test.yml#L82

**Comment by LecrisUT** [comment]
Cool, it seems very straightforward. Just have to test how it can be incorporated in a cmake workflow.

**Comment by danielealbano** [comment]
Mmm you can just run the commands that the lcov action runs internally in cmake but if I have to be honest I would keep them separated. 

To use only cmake you would need to carry out the whole series of steps (building tests, running tests, running lcov, doing upload).

Is there any specific reason for which you want to use cmake directly? Planning to switch to a different CI/CD platform?

**Comment by LecrisUT** [comment]
I mean, making sure I had configured the cmake project correctly so that I only need to run ctest (from lukka/run-cmake), this action and codecov. I also need to make sure to document how to do all of these manually.

Unfortunately I can't manage to hook `ctest -T Coverage` to be run automatically by the workflow. Maybe it can be done by CtestConfig.cmake. If that was possible the manual step would be to just run lcov and generate html files to preview.

And also yes, I want to copy my implementation from one project to another that uses a different CI/CD

**Comment by danielealbano** [comment]
I personally run the tests directly after they are built and not via cmake but I use Catch2 and all the tests are in 1 single binary and only that target is registered with ctest in my cmake.

**Comment by danielealbano** [comment]
@GitMensch although took "just" 9 months for me to make the PR to update the README, here we go

#9

**Comment by GitMensch** [comment]
Thank you, looks well!
